sailfishos/sailjail-permissions

permissions/Audio.permission
Needed by fm radio support.
@rainemak @Tomin1
=> [sailjail-permissions] Add audioroute service to Audio permissions. Contributes to JB#52175

permissions/Email.permission
Launch store for email app installation if not already installed.
=> [sailjail-permission] Allow talking to store. Fixes JB#52224

permissions/Phone.permission
Phone app can show about page with *#07# and needs to call
settings d-bus for that.
@rainemak @Tomin1
=> [permissions] Add jolla-settings to Phone permissions. Fixes JB#52483

permissions/Thumbnails.permission
Generating thumbnails for some file types is handled by library code
executing helper binaries (instead of using thumbnailer D-Bus service).
To facilitate this, the helper binaries must be visible to the sandboxed
application.
Add pdf and video thumbnail helpers to private-bin list.
Signed-off-by: Simo Piiroinen <simo.piiroinen@jolla.com>
=> [permissions] Add thumbnail helper binaries to private-bin. JB#52400

permissions/Downloads.permission, permissions/Music.permission, permissions/Pictures.permission
Add music, download and picture directories from android_storage that are indexed by Tracker to relevant permissions. Don't create them if they don't yet exist.
=> [permissions] Add common Android directories to permissions. Fixes JB#52685

permissions/Notifications.permission
This should be only needed by Lipstick for storing the notifications.
@Tomin1
=> [permissions] Remove notification database access. Fixes JB#52765

permissions/Calendar.permission, permissions/jolla-email.profile
The jolla-calendar app exposes a dbus interface that allows calendar
entries to be viewed and ics events to be imported.
This change allows apps with Calendar permissions access to this dbus
interface.
=> [permissions] Add dbus interface access to calendar permissions. Contributes to JB#52660

permissions/Accounts.permission
The keyprovider system used by some gallery plugins has user written
configuration here. Could be good to allow even if the static
data is commonly used.
@Tomin1 @rainemak
=> [sailjail-permissions] Add Keys dir to Accounts. Contributes to JB#52867

permissions/Base.permission, permissions/Email.permission, permissions/GnuPG.permission, permissions/jolla-email.profile
Fixes #15.
@spiiroin and @pvuorela this would allow to use crypto operations in jolla-email. It still requires to add the GnuPG permission to the jolla-email desktop file though.
Before the patch, you cannot sign an outgoing email.
=> Add a profile to allow GnuPG crypto operations

permissions/voicecall-ui.profile
Voicecall error dialog can request device reboot, needs dsme.
@Tomin1
=> [sailjail-permissions] Add dsme to voicecall permissions. Fixes JB#53293

tools/dependencies.py
This script allows to visualise permission relationships. It mostly
deals with includes of other permissions. This is useful to tell if
there are problematic implicit dependencies.
It also shows if permission can be directly included or if it's so
called internal permission. That heuristic is based on missing
translation category which is mostly correct indicator (there may be
false negatives).
Additionally it shows if permission defines privileged data directory.
Graphviz is required to use this tool.
=> Add script to visualise permission relationships.

permissions/Base.permission, permissions/Internet.permission
Now that maliit uses regular unix socket instead of an abstract one,
applications can be put into private net namespaces via "net none".
Which then needs to be undone for those applications that have been
granted internet access.
=> Default to "net none"

README.md, permissions/Base.permission, permissions/Documents.permission, permissions/Downloads.permission, permissions/Music.permission, permissions/Pictures.permission, permissions/Videos.permission
Hide well-know directories by default. These rules mount an empty
read-only directory on top of well-known directories unless the
respective permissions have been granted. Update documentation about
these rules. Also mention that libsailfishapp will set OrganizationName
and ApplicationName correctly.
=> Hide well-known directories by default

permissions/Base.permission, permissions/Email.permission
Messageserver (qmf) socket was moved to RUNUSER directory and rules need
adapting to that. Blacklist it by default so that applications without
access to email can't use it.
=> Adjust qmf socket path.

permissions/Location.permission
This is not needed for positioning to work.
=> Remove privileged-data from Location

permissions/Email.permission
Remove application specific paths from Email.permission. These are
either legacy and not used anymore, were never used, or they are
automatically allowed by sailjail.
Those mail_attachments rules didn't do anything as the directory access
is allowed anyway if app has Downloads permission. Also added a comment
about that dbus rule.
=> Remove application specific paths from Email.permission

README.md, permissions/Base.permission, permissions/PublicDir.permission, permissions/UserDirs.permission
Use includes to add permissions to `Downloads`, `Documents`, `Music`, `Pictures` and `Videos`. In addition include the common user directory `Public` but exclude `Templates` as unneeded and `Desktop` as not wanted our desktop files are handled differently.
Also fix a copy-paste error in `README.md`.
=> Add user common dirs permissions

README.md, permissions/Messages.permission, permissions/Phone.permission, permissions/PinQuery.permission
Move pin query dialog opening to its own permission but include that
from Phone and Messages. Also restrict this to pin query only as that
service name exposes some other interfaces as well.
Add a comment that this D-Bus API requires privileged access to
function. This permission is internal without any descriptions. As this
is only used through Phone and Messages those are not needed.
=> Move pin query to its own permission

README.md, permissions/Base.permission, permissions/DataStorages.permission, permissions/RemovableMedia.permission, permissions/UDisks.permission, permissions/UDisksListen.permission, tools/generate_translation_strings.py
[permissions] Use disable-mnt to control data storage perms, move udisk2 include. OMP#JOLLA-49
Block access to any media mount with disable-mnt in Base.permissions.
Grant permissions to all media when DataStorages permission is used,
including UDisks2 D-Bus.
Move the UDisks permission include away from Base.permissions. This is
to be included separately or via DataStorages permission.
=> Split UDisk2 permissions, Use disable-mnt to control data storage perms.

permissions/Accounts.permission, permissions/Audio.permission, permissions/Base.permission, permissions/Email.permission
Instead of using blacklists, use whitelist for ${RUNUSER}. This allows
better control over what application can see in that directory.
Needs [libsignon!11](https://git.sailfishos.org/mer-core/libsignon/merge_requests/11).
=> Use whitelisting for ${RUNUSER}

permissions/MediaIndexing.permission
Tracker1 still kept. That can be removed once the update is merged.
For this one shouldn't hurt integrating already before the update.
Related to https://git.sailfishos.org/mer-core/tracker/merge_requests/34
@Tomin1 @rainemak @llewelld
=> Add Tracker3 miner service to MediaIndexing

README.md, permissions/CommunicationHistory.permission, permissions/Messages.permission, permissions/Phone.permission, permissions/jolla-messages.profile, permissions/voicecall-ui.profile, tools/dependencies.py
Remove CommHistory specific permissions from Phone and Messages and move
those to separate CommunicationHistory.permission file. Allow only relevant D-Bus
interfaces.
Remove those old resource comments and add more useful comments for the
purposes of the rules.
Move settings permission outside Phone and Messages permission as
it doesn't belong here as it's about being able to open a Settings
page which is an application specific thing to do.
=> Add CommunicationHistory.permission.

permissions/sailfish-browser.profile
Fixes a regression introduced in 8125bba05f1352 which gave Base.permissions priority.
This change ensures sailfish-browser's ability to read/write to~/.local/share/applications isn't overridden by Base.permissions later.
I just followed the advice given in the bug report by @spiiroin and it works nicely, tested using the new [pop-up menu PR](https://github.com/sailfishos/sailfish-browser/pull/808).
=> Ensure sailfish-browser can add desktop icons

permissions/MediaIndexing.permission
This allows tracker-extract to run within a sandbox.
=> [permissions] Add access to tracker miner data to MediaIndexing. OMP#JOLLA-144 JB#54283

permissions/Pictures.permission, permissions/jolla-gallery.profile
Provide access to the cloud/social media images that are on the device
via Pictures permission. Remove the jolla-gallery.profile as unnecessary
(empty as of now).
=> Move privileged Images dir access to Pictures

permissions/Email.permission
The Email application should have the necessary permissions listed that
are then visible for the user. The includes used here wouldn't be shown.
=> Remove user dir includes from Email perms.

permissions/Messages.permission, permissions/jolla-messages.profile
Abstract the Telepathy access for messages by using organization and
application names in the D-Bus name ownership. These are supported via
--template in sailjail that will get the org and app names passed and
processed by firejail.
=> Abstract Telepathy access for messages.

permissions/Base.permission
DConf notifications are delivered on the ca.desrt.dconf.Writer interface
rather than simply ca.desrt.dconf.
=> [permissions] Fix applications not receiving dconf notifications. Fixes JB#54428

permissions/Base.permission, permissions/booster-browser.profile, permissions/booster-generic.profile, permissions/booster-qt5.profile, permissions/booster-silica-media.profile, permissions/booster-silica-qt5.profile, permissions/booster-silica-session.profile, permissions/booster.profile
Boosting sandboxed applications works by launching booster in sandbox.
Such application boosters use permissions for the the application they
are handling. Any additional sandboxing tweaks that are needed are
handled by use of booster type specific profile files.
Signed-off-by: Simo Piiroinen <simo.piiroinen@jolla.com>
=> Add booster profile files

README.md, config/50-default-profile.conf, rpm/sailjail-permissions.spec, sailjail-permissions.pro
Default profile defines the set of permissions that is applied when
application doesn't define any application profile for sandboxing. It
allows sandboxing of applications antedating sandboxing.
See also: https://github.com/sailfishos/sailjail/pull/50
=> Add default profile configuration

permissions/Base.permission
There is need to add /etc/kcapi folder to the Base.permission to allow applications to use additional crypto functionality.
=> [permissions] Add /etc/kcapi folder to the Base perms. Fixes JB#54719

permissions/Base.permission
Ensure the maliit-server socket directory exists prior to creating the
sandbox, to ensure that the directory will be mounted.
Otherwise, if the maliit-server is started after some other sandboxed
service or application, the original sandboxed service or application
will never get the maliit-server socket directory mounted for them.
=> [permissions] Create maliit-server socket directory. Contributes to JB#54741

permissions/voicecall-ui.profile, rpm/sailjail-permissions.spec
Add profile for voicecall-ui-prestart because it has different name from
the binary name. As it is the same application as voicecall-ui, use a
symbolic link.
Also remove extra stuff from voicecall-ui. Now that data directory is
set properly, we can also remove that FIXME and the whitelist line.
=> Add profile for voicecall-ui-prestart.

permissions/MediaIndexing.permission
Shouldn't be needed, though not much harm either. Mostly was getting
confused why I was getting back the directories even though trying
to delete them to save space.
@rainemak @Tomin1 @adenexter
=> [sailjail-permissions] Remove tracker1 content from MediaIndexing. JB#55207

permissions/WebView.permission, permissions/sailfish-browser.profile
This reverts commit 2c0dd6a82dda827386a382c980b6f91f2c7d7dd3.
There is no need for additional configuration, because applications
already have acess to the lib directory and its descendants.
=> [sailjail-permissions] Revert "Add support for gecko-camera. JB#55053"

permissions/Base.permission
[media] Give access to /etc/gst-droid to media and camera applications. Fixes JB#55372
Config there enables optional codecs such as h265, and specifies camera quirks on some devices.
=> media: Give access to /etc/gst-droid to media and camera applications

permissions/Accounts.permission
com.google.code.AccountsSSO.SingleSignOn is located on system bus.
Fixes error: `SignOn::ConnectionManager::init:130 - Unable to activate p2p signond service!` when attempting to create email-account.
=> [permissions] Fix libsignond bus permission. JB#55409

README.md, permissions/Base.permission
Include Sharing.permissions from Base.permissions.
Update documentation so that "Sharing" is listed under permissions
that applications should not use directly.
Signed-off-by: Simo Piiroinen <simo.piiroinen@jolla.com>
=> [permissions] Allow Sharing by default. Fixes JB#55380

permissions/Messages.permission
Messages app used to get this through Sharing.permission until it was
removed in 659c9354cb7ad33bd032de035a7993c503049ff8. That was of course
wrong but it made MMS sending work. Add rules to access MmsHandler to
Messages.permission to fix MMS sending.
=> [permissions] Add MmsHandler to Messages.permission. Fixes JB#55052

README.md, permissions/GnuPG.permission, permissions/Secrets.permission
…Bus.
Allow GnuPG pinentry to talk to the secrets daemon also.
This requires sailfishos/sailfish-secrets#178 to be merged.
Without these two PRs, the email signature in email application is failing.
@chriadam and @pvuorela, I've no real idea if the dbus-user entries I've put here make sense or not. If you may review or ask anyone else to review, that would be great. Thank you.
=> [sailjail-permissions] Add a permission to talk over secrets daemon DBus. Contributes to JB#56300

permissions/Base.permission
Data provider qml files, needed by the qml module, installed there.
@Tomin1 @spiiroin
=> [permissions] Add contextkit dir to base permissions. JB#56324

README.md, config/50-default-profile.conf, permissions/Compatibility.permission
Add Compatibility permission for default profile. This allows apps to
access selected binaries from /usr/bin. It has been used as a way around
certain library restrictions.
Please check if the list of binaries is sane and if it should have something
more or less. Also please check the descriptions.
See also https://github.com/sailfishos/sailjail/pull/69
=> Add Compatibility permission

permissions/voicecall-ui.profile
Phone application must be able to check lock state and talk to
com.jolla.csd to be able to launch it when a special phone number is
written. As it doesn't really need to access any methods on that bus
name, limit it to something that doesn't matter.
=> Allow checking lock state and starting csd for voicecall-ui

rpm/sailjail-permissions.spec
This is unnecessary after combining voicecall-ui.desktop and voicecall-ui-prestart.desktop.
=> Drop voicecall-ui-prestart.profile symlink

permissions/UDisksListen.permission
For the correct synchronization of the partition model, it is necessary to enable the UDisks2 service to listen to the signals of  `org.freedesktop.DBus.ObjectManager.*` and `org.freedesktop.DBus.Properties.*` interfaces.
Without them, the status of the partition is synchronized incorrectly (mounted or unmounted, etc.).
=> [permissions] Supplement broadcast permissions for UDisksListen. OMP#OS-5687

permissions/WebView.permission
The `${HOME}/Desktop` folder is blacklisted in Base permissions.
Disabling the blacklist for a folder must be before adding the folder to the whitelist.
=> [permissions] Remove folder required by WebView from blacklist. OMP#OS-10807

README.md
The README suggested there was a plan to sandbox all apps by the
Sailfish OS 4.4.0 release. In practice, this meant that all apps without
permissions specified would be given a default profile from 4.4.0
onwards.
Since this is now the case, this change updates the README to reflect
the current situation.
Fixes #126.
=> [permissions] Update README to clarify which apps are sandboxed. Fixes JB#58455

permissions/jolla-email.profile
The jolla-email app needs to open and close tabs in the external browser as part of the account creation flow (OAuth2). This change grants access to the org.sailfishos.browser.ui DBus interface for this purpose.
=> [permissions] Allow email to access browser ui. Fixes JB#58786

permissions/Messages.permission
The MmsHelper in libcommhistory is using two different mms services which have different services handling them. Other was included while the other was not.
@Tomin1 @monich
=> [permissions] Add missing MmsEngine permission to Messages. JB#56790

permissions/jolla-contacts.profile
The jolla-contacts app needs to open and close tabs in the external browser as part of the account creation flow (OAuth2) of the Import Contacts Wizard. This change grants access to the
org.sailfishos.browser.ui DBus interface for this purpose.
=> [permissions] Allow contacts to access browser ui. JB#59301

README.md
Adds some info about the Sharing permission for accessing the Share API,
specifically to clarify that it is available to all applications by
default.
=> [permissions] Add Sharing permission details to the README. Fixes JB#58483

permissions/Compatibility.permission
First off; many thanks for adding this originally.
I really had no idea if i could change over in time for 4.4.
But SeaPrint 1.0 seems to have been a success, so now these are not needed anymore.
I have something like one-and-a-half report that something stopped working compared to 0.9, but they never followed up... so should be fine.
For discussion: could be sensible waiting another minor-version of SFOS before merging.
For discussion 2: I would be open to (try to) contribute to share-as-pdf for Sailfish-Office so Calligraconverter can be dropped, but afaict there is no "neutral ground" to hand over such files. Feel free to poke me in IRC or the forums as well.
=> [permissions] Remove PDF tools

permissions/Base.permission, rpm/sailjail-permissions.spec
Firejail 0.9.72 no longer uses or includes disable-passwdmgr.inc. Having it present in sailjail-permissions causes sailjail to fail to launch with the newer firejail.
=> [sailjail-permissions] Remove disable-passwdmgr.inc. Contributes to JB#59121

README.md
The Privileged permission should be part of other permissions where needed. In general there shouldn't be reasons for applications to use Privileged permission directly.
=> [permissions] Move Privileged permission to internal list. JB#60573

permissions/Email.permission
The message server is not using a specific
socket file, but is now using DBus.
@pvuorela, this could be usefull to test the QMF switch to DBus on device.
=> [sailjail-permissions] Move Email permission to DBus.
